apiVersion: apps/v1
kind: Deployment
metadata:
  name: logoutput-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logoutput
  template:
    metadata:
      labels:
        app: logoutput
    spec:
      volumes:
        - name: shared-log-file
          emptyDir: {}
      containers:
        - name: logoutput-server
          image: hexa4d/log_output:1.10s
          volumeMounts:
            - name: shared-log-file
              mountPath: /app/shared
        - name: logoutput-generator
          image: hexa4d/log_output:1.10g
          volumeMounts:
            - name: shared-log-file
              mountPath: /app/shared
